version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words: []
ignoreWords:
  - checkwinsize
  - dircolors
  - fgrep
  - histappend
  - ignoreboth
  - lesspipe
  - libpam
  - myaosato
  - rxvt
  - setaf
  - setf
  - SHOWDIRTYSTATE
  - SHOWSTASHSTATE
  - SHOWUNTRACKEDFILES
  - SHOWUPSTREAM
  - vdir
import:
  - ./cspell.local.yaml
